### ISSUE TITLE
Using package-json behind proxy

### ISSUE THREAD

**Issue by JochenHoertreiter** [sindresorhus/package-json#43] opened 2018-03-26 09:14 UTC
Module "got" allows usage of http tunneling to work behind a proxy.
package-json doesn't seem to handle given htttp/https proxies (either within npm config or env)
and is not working behind a proxy (RequestError: connect ETIMEDOUT)

**Comment by sindresorhus** [comment] 2018-03-26 09:29
Duplicate of #22

**Closed by sindresorhus** 2018-03-26 09:29 UTC
